{
  "hash": "4ffa18fc68286a3bc56caa7b8b63e7fd",
  "result": {
    "markdown": "---\ntitle: Gov't debt is savings of the workers for retirement\nauthor: Mitsuo Shiota\ndate: '2021-05-06'\ncategories:\n  - economics\n  - Nikkei\n  - R\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n## Is gov't debt a morale issue?\n\n\"Lecture on Economics\" in Nikkei news paper on May 3 to 5, 2021 was titled \"Think about the burden for future generations.\" Lectures are [here](https://www.nikkei.com/article/DGXZQOCD163O50W1A410C2000000/), [here](https://www.nikkei.com/article/DGXZQOCD1649E0W1A410C2000000/) and [here](https://www.nikkei.com/article/DGXZQOCD225QK0S1A420C2000000/) (Japanese, subscription required). The authors think that lack of government morale causes government debt. They think politicians are not well disciplined, and are weak under the pressure from spend-demanding and tax-averse electorate.\n\nSo the first proposes a debt rollover restriction rule, to which I have strong objection. Don't forget [the U.S. debt ceiling crisis under the Obama administration and the Republican controlled House](https://en.wikipedia.org/wiki/United_States_debt-ceiling_crisis_of_2011). The second proposes independent fiscal institutions, of which effectiveness I doubt. The third proposes Covid-19 measures should be financed by taxes, not by deficits, because deficits divert resources from productive capital accumulation. He may be right, if the deficits crowd out investment by causing higher interest rates. But now I observe persistent zero interest rates, and no crowding-out.\n\nSo I don't think government debt is a morale issue.\n\n## Is gov't debt a burden for future generations?\n\nNikkei title is \"Think about the burden for future generations.\" Is government debt a burden for future generations in the first place?\n\nPaul Krugman says no. \"Debt is Money We Owe to Ourselves.\" ([here](https://krugman.blogs.nytimes.com/2015/02/06/debt-is-money-we-owe-to-ourselves/)) Dean Baker says no. \"There is a distributional issue --- Bill Gates' children may own all the debt --- but that is within generations, not between generations.\" ([here](https://krugman.blogs.nytimes.com/2011/12/28/debt-is-mostly-money-we-owe-to-ourselves/))\n\nSimon Wren-Lewis says yes, if we consider overlapping generations. \"Government debt can be a burden on future generations.\" ([here](https://mainlymacro.blogspot.com/2012/10/the-burden-of-government-debt.html))\n\n## Two meanings of \"generation\"\n\nWhich side is right? I think both sides are right. According to Oxford Languages via Google, \"generation\" meanings are:\n\n1.  the average period, generally considered to be about thirty years, in which children grow up, become adults, and have children of their own.\n\n2.  all of the people born and living at about the same time, regarded collectively.\n\nPaul Krugman and Dean Baker are right if they use \"generation\" as 1, and Simon Wren-Lewis is right if he uses \"generation\" as 2.\n\nLet us call 1 as \"Period\" and 2 as \"Generation,\" then I can show Generation overlap as below. Every Generation lives in 2 Periods. For example, Generation 2 lives working in Period 1 and lives retired in Period 2.\n\n![Period Generation Matrix](images/test.png){#fig-matrix fig-alt=\"Period Generation Matrix\"}\n\n## A tiny model\n\nTo clarify my understanding, I make a tiny model to replicate above table. You can see my tiny model at tiny_model function in [the Rmarkdown format of this post](https://github.com/mitsuoxv/blog-source/blob/master/content/post/2021-05-06-gov-t-debt-is-savings-of-the-workers-for-retirement/index.Rmd).\n\nImagine a one factor (labor), three sector (Generation 1 and 2, Government), and closed economy. There is no capital, no business sector, no international trade, and no foreigner. Ignore financial sector as an intermediary. And imagine all goods and services produced in a Period are perishable, and must be consumed in that Period, like foodstuff and entertainment, care and medicine services. There is no stock, and no investment. And imagine the only role of Government is to issue and pay back bonds, of which duration is one Period, 30 years. There is no defense spending, and no taxes. The only method for Generation to save is to buy bonds.\n\n### Constant saving rate, with constant population and productivity\n\nIn Period 1, Generation 1 and Generation 2 lives, but only Generation 2 works. If the population in Generation 2 is 100 persons, and the productivity in Period 1 is 20 yen per person, 2000 yen worth goods and services are produced.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiny_model <- function(population_growth, productivity_growth, saving_rate = NULL) {\n  by_generation <- tibble(\n    Generation = 1:7,\n    population = 100 * c(1, cumprod(population_growth)),\n    reproduce_rate = c(population_growth, NA)\n  )\n  \n  by_period <- tibble(\n    Period = 1:6,\n    pop_retired = by_generation$population[-7],\n    pop_working = by_generation$population[-1],\n    productivity = 20 * c(1, cumprod(productivity_growth))\n  )\n  \n  by_period <- by_period %>% \n    mutate(\n      pop_total = pop_retired + pop_working,\n      retired_ratio_pop = pop_retired / pop_total,\n      GDP = productivity * pop_working\n    )\n  \n  if (is.null(saving_rate)) {\n    saving_rate <- by_period$retired_ratio_pop\n  }\n  \n  by_period <- by_period %>% \n    mutate(\n      consump_working = GDP * (1 - saving_rate),\n      consump_retired = GDP - consump_working,\n      percap_cons_wk = consump_working / pop_working,\n      percap_cons_re = consump_retired / pop_retired,\n      # real interest rate per year\n      annual_interest_rate = ((consump_retired / lag(consump_retired))^(1/30) - 1) * 100,\n      debt_GDP_ratio = consump_retired / GDP\n    )\n\n  by_generation <- by_generation %>% \n    bind_cols(\n      tibble(\n          consump_working = c(NA, by_period$consump_working[-11]),\n          consump_retired = c(by_period$consump_retired, NA)\n      )\n    )\n  \n  by_generation <- by_generation %>% \n    mutate(\n      consumption = consump_working + consump_retired,\n      income_from_work = c(NA, by_period$GDP),\n      income_from_interest = consumption - income_from_work,\n      percap_consump = consumption / population,\n      percap_income_from_work = income_from_work / population,\n      percap_income_from_interest = income_from_interest / population,\n      percap_cons_wk = c(NA, by_period$percap_cons_wk),\n      percap_cons_re = percap_consump - percap_cons_wk\n      )\n  \n  list(\n    by_period = by_period,\n    by_generation = by_generation\n  )\n}\n```\n:::\n\n\nFrom Period 2 and on, let us assume population by Generation is constant 100 persons, population by Period is constant 200 persons, and productivity is constant 20 yen per person. And let us assume working Generation and retired Generation in each Period agree to share the produced so that each person can consume equally. As each working Generation consume half of what they produce, the saving rate is 0.5.\n\n\n::: {#tbl-model1_table1 .cell tbl-cap='Population by Period'}\n\n```{.r .cell-code}\n# multiplier by Generation, 30 years, is constant 1 for Generation 2 to 7\npopulation_growth <- rep(1, 6)\n\n# multiplier by Period, 30 years, is constant 1 for Period 2 to 6\nproductivity_growth <- rep(1, 5) \n\nmodel1 <- tiny_model(population_growth, productivity_growth)\n\nmodel1$by_period %>% \n  select(Period, pop_total, pop_retired, pop_working, retired_ratio_pop) %>% \n  knitr::kable(\n    col.names = c(\n      \"Period\",\n      \"Population Total (persons)\",\n      \"Population Retired (persons)\",\n      \"Population Working (persons)\",\n      \"Ratio of Retired\"\n      )\n    )\n```\n\n::: {.cell-output-display}\n| Period| Population Total (persons)| Population Retired (persons)| Population Working (persons)| Ratio of Retired|\n|------:|--------------------------:|----------------------------:|----------------------------:|----------------:|\n|      1|                        200|                          100|                          100|              0.5|\n|      2|                        200|                          100|                          100|              0.5|\n|      3|                        200|                          100|                          100|              0.5|\n|      4|                        200|                          100|                          100|              0.5|\n|      5|                        200|                          100|                          100|              0.5|\n|      6|                        200|                          100|                          100|              0.5|\n:::\n:::\n\n::: {#tbl-model1_table2 .cell tbl-cap='Production and Consumption per person by Period'}\n\n```{.r .cell-code}\nmodel1$by_period %>% \n  select(Period, productivity, percap_cons_wk, percap_cons_re) %>% \n  knitr::kable(\n    col.names = c(\n      \"Period\", \"Productivity (yen/person)\",\n      \"Consumption by Working (yen/person)\",\n      \"Consumption by Retired (yen/person)\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n| Period| Productivity (yen/person)| Consumption by Working (yen/person)| Consumption by Retired (yen/person)|\n|------:|-------------------------:|-----------------------------------:|-----------------------------------:|\n|      1|                        20|                                  10|                                  10|\n|      2|                        20|                                  10|                                  10|\n|      3|                        20|                                  10|                                  10|\n|      4|                        20|                                  10|                                  10|\n|      5|                        20|                                  10|                                  10|\n|      6|                        20|                                  10|                                  10|\n:::\n:::\n\n::: {#tbl-model1_table3 .cell tbl-cap='Production and Consumption by Period'}\n\n```{.r .cell-code}\nmodel1$by_period %>% \n  select(Period, GDP:consump_retired, debt_GDP_ratio) %>% \n  knitr::kable(\n    col.names = c(\n      \"Period\", \"GDP (yen)\",\n      \"Consumption by Working (yen)\",\n      \"Consumption by Retired (yen)\",\n      \"Government debt to GDP ratio = Saving rate\"\n      )\n  )\n```\n\n::: {.cell-output-display}\n| Period| GDP (yen)| Consumption by Working (yen)| Consumption by Retired (yen)| Government debt to GDP ratio = Saving rate|\n|------:|---------:|----------------------------:|----------------------------:|------------------------------------------:|\n|      1|      2000|                         1000|                         1000|                                        0.5|\n|      2|      2000|                         1000|                         1000|                                        0.5|\n|      3|      2000|                         1000|                         1000|                                        0.5|\n|      4|      2000|                         1000|                         1000|                                        0.5|\n|      5|      2000|                         1000|                         1000|                                        0.5|\n|      6|      2000|                         1000|                         1000|                                        0.5|\n:::\n:::\n\n\nEach Generation n produces 20 yen per person in Period n-1 , and consumes 10 yen in Period n-1 and 10 yen in Period n, 20 yen in total. Note that every yen value is in real, denoted in Period 1 price level yen.\n\n\n::: {#tbl-model1_table4 .cell tbl-cap='Consumption per person by Generation'}\n\n```{.r .cell-code}\nmodel1$by_generation %>% \n  select(Generation, population, percap_consump, percap_cons_wk, percap_cons_re) %>% \n  knitr::kable(\n    col.names = c(\n      \"Generation\", \"Population (persons)\",\n      \"Consumption in Total (yen/person)\",\n      \"Consumption in Working (yen/person)\",\n      \"Consumption in Retired (yen/person)\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n| Generation| Population (persons)| Consumption in Total (yen/person)| Consumption in Working (yen/person)| Consumption in Retired (yen/person)|\n|----------:|--------------------:|---------------------------------:|-----------------------------------:|-----------------------------------:|\n|          1|                  100|                                NA|                                  NA|                                  NA|\n|          2|                  100|                                20|                                  10|                                  10|\n|          3|                  100|                                20|                                  10|                                  10|\n|          4|                  100|                                20|                                  10|                                  10|\n|          5|                  100|                                20|                                  10|                                  10|\n|          6|                  100|                                20|                                  10|                                  10|\n|          7|                  100|                                NA|                                  10|                                  NA|\n:::\n:::\n\n\n### Unfunded gift and its reversal\n\nNow imagine, in Period 2, Generation 2 and 3 agree to change sharing ratio from 50:50 to 60:40 by Generation 3 buying additional bonds and Government giving the received money to Generation 2. Generation 3's saving rate changes from 0.5 to 0.6. Generation 3 may have been persuaded, as consumption in life will be unchanged 20 yen per person if the same custom continues, that is Generation 4 will save 0.6 in Period 3. Generation 2 can benefit from this deal, as they can consume 22 yen per person more than 20 yen they produce in life.\n\nAnd imagine, in Period 5, Generation 5 and 6 agree to abolish this custom for some reason. Generation 5 can consume only 18 yen per person in life. Consumption of 2 yen per person is transferred to Generation 2 from Generation 5, a future generation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 0.5 in Period 1, 0.6 in Period 2 to 4, and 0.5 in Period 5 to 6\nsaving_rate <- c(0.5, rep(0.6, 3), rep(0.5, 2)) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# multiplier by Generation, 30 years, is constant 1 for Generation 2 to 7\npopulation_growth <- rep(1, 6)\n\n# multiplier by Period, 30 years, is constant 1 for Period 2 to 6\nproductivity_growth <- rep(1, 5) \n\nmodel2 <- tiny_model(population_growth, productivity_growth, saving_rate)\n```\n:::\n\n::: {#tbl-model2_table1 .cell tbl-cap='Production and Consumption by Period'}\n\n```{.r .cell-code}\nmodel2$by_period %>% \n  select(Period, GDP:consump_retired, debt_GDP_ratio) %>% \n  knitr::kable(\n    col.names = c(\n      \"Period\", \"GDP (yen)\",\n      \"Consumption by Working (yen)\",\n      \"Consumption by Retired (yen)\",\n      \"Government debt to GDP ratio = Saving rate\"\n      )\n  )\n```\n\n::: {.cell-output-display}\n| Period| GDP (yen)| Consumption by Working (yen)| Consumption by Retired (yen)| Government debt to GDP ratio = Saving rate|\n|------:|---------:|----------------------------:|----------------------------:|------------------------------------------:|\n|      1|      2000|                         1000|                         1000|                                        0.5|\n|      2|      2000|                          800|                         1200|                                        0.6|\n|      3|      2000|                          800|                         1200|                                        0.6|\n|      4|      2000|                          800|                         1200|                                        0.6|\n|      5|      2000|                         1000|                         1000|                                        0.5|\n|      6|      2000|                         1000|                         1000|                                        0.5|\n:::\n:::\n\n::: {#tbl-model2_table2 .cell tbl-cap='Consumption per person by Generation'}\n\n```{.r .cell-code}\nmodel2$by_generation %>% \n  select(Generation, population, percap_consump, percap_cons_wk, percap_cons_re) %>% \n  knitr::kable(\n    col.names = c(\n      \"Generation\", \"Population (persons)\",\n      \"Consumption in Total (yen/person)\",\n      \"Consumption in Working (yen/person)\",\n      \"Consumption in Retired (yen/person)\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n| Generation| Population (persons)| Consumption in Total (yen/person)| Consumption in Working (yen/person)| Consumption in Retired (yen/person)|\n|----------:|--------------------:|---------------------------------:|-----------------------------------:|-----------------------------------:|\n|          1|                  100|                                NA|                                  NA|                                  NA|\n|          2|                  100|                                22|                                  10|                                  12|\n|          3|                  100|                                20|                                   8|                                  12|\n|          4|                  100|                                20|                                   8|                                  12|\n|          5|                  100|                                18|                                   8|                                  10|\n|          6|                  100|                                20|                                  10|                                  10|\n|          7|                  100|                                NA|                                  10|                                  NA|\n:::\n:::\n\n\nBut is this Generation 5 worse-off caused by the burden of government debt on future Generations?\n\nNow, suppose Government suddenly discovers a new way to transfer buying power across Generation other than issuing additional bonds. The new way is tax and transfer payment, like pay-go based pension system. You may cry foul, claiming this should also be counted as government debt, though this is not bond balance. You may be right in accounting, but you can feel the difference between government debt and government promise in pension system is not solid but fluid.\n\nFrom this thought experiment, I would like to say the burden on future Generations is not government debt per se, but legacy social contract on how to share. Social contract made between Generation 2 and 3 becomes a legacy. Because of this legacy, Generation 3 and 4 in Period 4, and Generation 4 and 5 in Period 5 agree to share 60:40. But Generation 5 and 6 fail to keep this legacy in Period 6. This legacy turns out to be the burden on Generation 5. Generation 6 is now free from this burdensome legacy.\n\n## Population bonus and onus\n\nIn above simulation, Generation 2 is better off and Generation 5 is worse off. Is this kind of situation rare? No. If we assume population increases and decreases, there happens population bonus and onus.\n\nBelow is a rough image of population changes in Japan. Generation 1 works in Period 0: 1880-1910, and Generation 7 works in Period 6: 2060-2090. In Period 4: 2000-2030, Generation 4 is retired and Generation 5 is working. Although I am in the middle of Generation 4 and 5 in reality, let us read below as if we are Generation 5.\n\nI assume no productivity growth. And I assume Generation n and Generation n-1 agree to share the produced by population ratio so that each person can consume equally in each Period. So government debt to GDP ratio, which is the same as the saving rate and the ratio of consumption by the retired to total consumption by definition in this model, is exactly same as population ratio of the retired in each Period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# multiplier by Generation, 30 years, is:\n# 1.3 for Generation 2 to 4, 0.8 for Generation 5, 0.65 for Generation 6 to 7\npopulation_growth <- c(rep(1.3, 3), 0.8, rep(0.65, 2))\n\n# multiplier by Period, 30 years, is constant 1 for Period 2 to 6\nproductivity_growth <- rep(1, 5) \n\nmodel3 <- tiny_model(population_growth, productivity_growth)\n```\n:::\n\n::: {#tbl-model3_table1 .cell tbl-cap='Population by Generation'}\n\n```{.r .cell-code}\nmodel3$by_generation %>% \n  select(Generation, population, reproduce_rate) %>% \n  knitr::kable(\n    col.names = c(\n      \"Generation\", \"Population (persons)\",\n      \"Reproduce rate\"\n    ),\n    digits = c(rep(0, 2), 2)\n  )\n```\n\n::: {.cell-output-display}\n| Generation| Population (persons)| Reproduce rate|\n|----------:|--------------------:|--------------:|\n|          1|                  100|           1.30|\n|          2|                  130|           1.30|\n|          3|                  169|           1.30|\n|          4|                  220|           0.80|\n|          5|                  176|           0.65|\n|          6|                  114|           0.65|\n|          7|                   74|             NA|\n:::\n:::\n\n::: {#tbl-model3_table2 .cell tbl-cap='Population by Period'}\n\n```{.r .cell-code}\nmodel3$by_period %>% \n  select(Period, pop_total, pop_retired, pop_working, retired_ratio_pop) %>% \n  knitr::kable(\n    col.names = c(\n      \"Period\",\n      \"Population Total (persons)\",\n      \"Population Retired (persons)\",\n      \"Population Working (persons)\",\n      \"Ratio of Retired\"\n      ),\n    digits = c(rep(0, 4), 2)\n    )\n```\n\n::: {.cell-output-display}\n| Period| Population Total (persons)| Population Retired (persons)| Population Working (persons)| Ratio of Retired|\n|------:|--------------------------:|----------------------------:|----------------------------:|----------------:|\n|      1|                        230|                          100|                          130|             0.43|\n|      2|                        299|                          130|                          169|             0.43|\n|      3|                        389|                          169|                          220|             0.43|\n|      4|                        395|                          220|                          176|             0.56|\n|      5|                        290|                          176|                          114|             0.61|\n|      6|                        189|                          114|                           74|             0.61|\n:::\n:::\n\n::: {#tbl-model3_table3 .cell tbl-cap='Production and Consumption by Period'}\n\n```{.r .cell-code}\nmodel3$by_period %>% \n  select(Period, GDP:consump_retired, debt_GDP_ratio, annual_interest_rate) %>% \n  knitr::kable(\n    col.names = c(\n      \"Period\", \"GDP (yen)\",\n      \"Consumption by Working (yen)\",\n      \"Consumption by Retired (yen)\",\n      \"Government debt to GDP ratio = Saving rate\",\n      \"Interest rate (percent)\"\n      ),\n    digits = c(rep(0, 4), rep(2, 2))\n  )\n```\n\n::: {.cell-output-display}\n| Period| GDP (yen)| Consumption by Working (yen)| Consumption by Retired (yen)| Government debt to GDP ratio = Saving rate| Interest rate (percent)|\n|------:|---------:|----------------------------:|----------------------------:|------------------------------------------:|-----------------------:|\n|      1|      2600|                         1470|                         1130|                                       0.43|                      NA|\n|      2|      3380|                         1910|                         1470|                                       0.43|                    0.88|\n|      3|      4394|                         2484|                         1910|                                       0.43|                    0.88|\n|      4|      3515|                         1562|                         1953|                                       0.56|                    0.07|\n|      5|      2285|                          900|                         1385|                                       0.61|                   -1.14|\n|      6|      1485|                          585|                          900|                                       0.61|                   -1.43|\n:::\n:::\n\n\nGeneration 2 worked in Period 1 and saved 1130 yen, and can consume 1470 yen in Period 2. How come? We can interpret this as Generation 2 earned interest income from saving, and the interest rate of bonds is 0.88 percent annually.\n\nGeneration 5 saved 1953 yen in Period 4, but can consume only 1385 in Period 5. We can interpret this as Generation 5 earned negative interest rate, -1.14 percent, in Period 5.\n\nAs the yen value is denoted in real terms, at Period 1 price level, interest rate is real interest rate. In this model, safe real interest rate is endogenous. Positive interest rate is a bonus, and negative one is an onus from population changes.\n\n\n::: {#tbl-model3_table4 .cell tbl-cap='Consumption per person by Generation'}\n\n```{.r .cell-code}\nmodel3$by_generation %>% \n  select(Generation, population, percap_consump, percap_cons_wk, percap_cons_re) %>% \n  knitr::kable(\n    col.names = c(\n      \"Generation\", \"Population (persons)\",\n      \"Consumption in Total (yen/person)\",\n      \"Consumption in Working (yen/person)\",\n      \"Consumption in Retired (yen/person)\"\n    ),\n    digits = c(rep(0, 2), rep(1, 3))\n  )\n```\n\n::: {.cell-output-display}\n| Generation| Population (persons)| Consumption in Total (yen/person)| Consumption in Working (yen/person)| Consumption in Retired (yen/person)|\n|----------:|--------------------:|---------------------------------:|-----------------------------------:|-----------------------------------:|\n|          1|                  100|                                NA|                                  NA|                                  NA|\n|          2|                  130|                              22.6|                                11.3|                                11.3|\n|          3|                  169|                              22.6|                                11.3|                                11.3|\n|          4|                  220|                              20.2|                                11.3|                                 8.9|\n|          5|                  176|                              16.8|                                 8.9|                                 7.9|\n|          6|                  114|                              15.8|                                 7.9|                                 7.9|\n|          7|                   74|                                NA|                                 7.9|                                  NA|\n:::\n:::\n\n\nEach Generation produces 20 yen per person. Generation 2 and 3 consumes more than 20 yen, Generation 4 consumes approximately 20 yen, and Generation 5 and 6 consumes less than 20 yen.\n\n\n::: {#tbl-model3_table5 .cell tbl-cap='Consumption and Income per person by Generation'}\n\n```{.r .cell-code}\nmodel3$by_generation %>% \n  select(Generation, percap_consump, percap_income_from_work, percap_income_from_interest) %>% \n  knitr::kable(\n    col.names = c(\n      \"Generation\", \"Consumption in Total (yen/person)\",\n      \"Income in Working (yen/person)\",\n      \"Income in Retired (interest income) (yen/person)\"\n    ),\n    digits = c(0, rep(1, 3))\n\n  )\n```\n\n::: {.cell-output-display}\n| Generation| Consumption in Total (yen/person)| Income in Working (yen/person)| Income in Retired (interest income) (yen/person)|\n|----------:|---------------------------------:|------------------------------:|------------------------------------------------:|\n|          1|                                NA|                             NA|                                               NA|\n|          2|                              22.6|                             20|                                              2.6|\n|          3|                              22.6|                             20|                                              2.6|\n|          4|                              20.2|                             20|                                              0.2|\n|          5|                              16.8|                             20|                                             -3.2|\n|          6|                              15.8|                             20|                                             -4.2|\n|          7|                                NA|                             20|                                               NA|\n:::\n:::\n\n\nWe, Generation 5, can consume 16.8 yen per person, less than 20 yen we produce. Why is interest income from holding bonds negative? Isn't this unfair? In theory, this is because we chose to have fewer children, Generation 6, who produce and share in Period 5. But as we, Generation 5, outnumber Generation 6, we may fight politically and get larger share in Period 5. This is so called \"Silver Democracy.\" If we do so, government debt to GDP ratio jumps from current 0.61. And this social contract on how to share may become the burdensome legacy for future Generations.\n\n## Add productivity growth and stagnation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reproduce rate over Generation, 30 years:\npopulation_growth <- c(rep(1.3, 3), 0.8, rep(0.65, 2))\n\n# Annual growth rates in percent from Period 2 to 6\nprod_gr_annual <- c(2, 8, 1, 0, 0)\n\nproductivity_growth <- ((prod_gr_annual + 100) / 100) ^ 30\n```\n:::\n\n\nNext, I change the assumption of productivity from constant to growing by annual rate of 2, 8, 1, 0, 0 percent in Period 2 to 6 respectively.\n\nI assume Generation n and Generation n-1 agree to share the produced by population ratio so that each person can consume equally in each Period. No \"Silver Democracy.\"\n\n\n::: {#tbl-model4_table1 .cell tbl-cap='Production and Consumption per person by Period'}\n\n```{.r .cell-code}\nmodel4 <- tiny_model(population_growth, productivity_growth)\n\nmodel4$by_period %>% \n  select(Period, productivity, percap_cons_wk, percap_cons_re) %>% \n  knitr::kable(\n    col.names = c(\n      \"Period\", \"Productivity (yen/person)\",\n      \"Consumption by Working (yen/person)\",\n      \"Consumption by Retired (yen/person)\"\n    ),\n    digits = c(rep(0, 4))\n  )\n```\n\n::: {.cell-output-display}\n| Period| Productivity (yen/person)| Consumption by Working (yen/person)| Consumption by Retired (yen/person)|\n|------:|-------------------------:|-----------------------------------:|-----------------------------------:|\n|      1|                        20|                                  11|                                  11|\n|      2|                        36|                                  20|                                  20|\n|      3|                       365|                                 206|                                 206|\n|      4|                       491|                                 218|                                 218|\n|      5|                       491|                                 194|                                 194|\n|      6|                       491|                                 194|                                 194|\n:::\n:::\n\n::: {#tbl-model4_table2 .cell tbl-cap='Production and Consumption by Period'}\n\n```{.r .cell-code}\nmodel4$by_period %>% \n  select(Period, GDP:consump_retired, debt_GDP_ratio, annual_interest_rate) %>% \n  knitr::kable(\n    col.names = c(\n      \"Period\", \"GDP (yen)\",\n      \"Consumption by Working (yen)\",\n      \"Consumption by Retired (yen)\",\n      \"Government debt to GDP ratio = Saving rate\",\n      \"Interest rate (percent)\"\n      ),\n    digits = c(rep(0, 4), rep(2, 2))\n  )\n```\n\n::: {.cell-output-display}\n| Period| GDP (yen)| Consumption by Working (yen)| Consumption by Retired (yen)| Government debt to GDP ratio = Saving rate| Interest rate (percent)|\n|------:|---------:|----------------------------:|----------------------------:|------------------------------------------:|-----------------------:|\n|      1|      2600|                         1470|                         1130|                                       0.43|                      NA|\n|      2|      6122|                         3460|                         2662|                                       0.43|                    2.90|\n|      3|     80090|                        45268|                        34822|                                       0.43|                    8.95|\n|      4|     86359|                        38382|                        47977|                                       0.56|                    1.07|\n|      5|     56134|                        22113|                        34020|                                       0.61|                   -1.14|\n|      6|     36487|                        14374|                        22113|                                       0.61|                   -1.43|\n:::\n:::\n\n::: {#tbl-model4_table3 .cell tbl-cap='Consumption per person by Generation'}\n\n```{.r .cell-code}\nmodel4$by_generation %>% \n  select(Generation, population, percap_consump, percap_cons_wk, percap_cons_re) %>% \n  knitr::kable(\n    col.names = c(\n      \"Generation\", \"Population (persons)\",\n      \"Consumption in Total (yen/person)\",\n      \"Consumption in Working (yen/person)\",\n      \"Consumption in Retired (yen/person)\"\n    ),\n    digits = c(rep(0, 5))\n  )\n```\n\n::: {.cell-output-display}\n| Generation| Population (persons)| Consumption in Total (yen/person)| Consumption in Working (yen/person)| Consumption in Retired (yen/person)|\n|----------:|--------------------:|---------------------------------:|-----------------------------------:|-----------------------------------:|\n|          1|                  100|                                NA|                                  NA|                                  NA|\n|          2|                  130|                                32|                                  11|                                  20|\n|          3|                  169|                               227|                                  20|                                 206|\n|          4|                  220|                               424|                                 206|                                 218|\n|          5|                  176|                               412|                                 218|                                 194|\n|          6|                  114|                               387|                                 194|                                 194|\n|          7|                   74|                                NA|                                 194|                                  NA|\n:::\n:::\n\n::: {#tbl-model4_table4 .cell tbl-cap='Consumption and Income per person by Generation'}\n\n```{.r .cell-code}\nmodel4$by_generation %>% \n  select(Generation, percap_consump, percap_income_from_work, percap_income_from_interest) %>% \n  knitr::kable(\n    col.names = c(\n      \"Generation\", \"Consumption in Total (yen/person)\",\n      \"Income in Working (yen/person)\",\n      \"Income in Retired (interest income) (yen/person)\"\n    ),\n    digits = c(rep(0, 4))\n\n  )\n```\n\n::: {.cell-output-display}\n| Generation| Consumption in Total (yen/person)| Income in Working (yen/person)| Income in Retired (interest income) (yen/person)|\n|----------:|---------------------------------:|------------------------------:|------------------------------------------------:|\n|          1|                                NA|                             NA|                                               NA|\n|          2|                                32|                             20|                                               12|\n|          3|                               227|                             36|                                              190|\n|          4|                               424|                            365|                                               60|\n|          5|                               412|                            491|                                              -79|\n|          6|                               387|                            491|                                             -104|\n|          7|                                NA|                            491|                                               NA|\n:::\n:::\n\n\nShocking result for us, Generation 5! We consume 412 yen per person, which is less than 491 yen we produce, and less than 424 yen Generation 4 consumes. Generation 5 is the first generation to become poorer than preceding Generation.\n\nThis happens because I assume that productivity growth is zero in Period 5 when Generation 6 works, and that population reproduce rate by Generation 5 is less than 1.\n\n## Multi-equilibrium hypothesis on inflation\n\nInterest rate in Period 5, 2030-2060, is negative, -1.14 percent. That is the return by holding bonds for Generation 5 who live retired in Period 5. How can we get negative interest rate? The answer is inflation. Nominal interest rate can't be much negative as long as paper money remains as an alternative way of saving. But real interest rate can be negative with inflation.\n\nThis simulation suggests that it is possible for Bank of Japan to achieve 2 percent inflation target before long, as interest rate in Period 5 can be interpreted as a return rate we get by buying bonds in 2015 and selling in 2045 on average. Inflation is 2 percent, nominal interest rate is 0.86, and real interest rate is -1.14 on average from 2015 to 2045.\n\nOf course, this is a simulation, not a prediction. But I can say that aging and decreasing population and stagnant productivity growth leads to inflation eventually in this model. Is this model, which assumes one factor no business sector closed economy, too unrealistic? In reality, there is business and foreign sector, investment, international trade and wage negotiation. Aging and decreasing population prompts businesses to reduce investment. Stagnant productivity growth prompts businesses to be tough in wage negotiations. Balassa-Samuelson effect works in reverse. Does aging and decreasing population and stagnant productivity growth lead to deflation, instead of inflation, in reality?\n\nI am not sure whether I can and should expand this model by adding factors and sectors to make it closer to reality. So I would like to propose my thinking as a hypothesis. I think there exists multi-equilibrium on inflation. Although prospect for Generation 6 population is close to certain, prospect for productivity growth is still uncertain. We are often told we will be replaced by AI in the work place. If it is true, it will be a huge jump in productivity. Abundant production capacity can satisfy all the demands. As long as we believe so, there is no inflation pressure. This is the first equilibrium. But if productivity growth statistics continues to show otherwise and to disappoint us, we Generation 5 will someday accept the idea that we can't consume as much as we saved, and that we must be poorer than Generation 4. On that day, we rush to consume by trying to get more share of consumption from each other in Generation 5 and/or from Generation 6. As buying power exceeds production capacity, inflation pressure mounts, and inflation will come. This is the second equilibrium. I am not hinting at hyper-inflation. Modest inflation is enough.\n\nThank you for reading a long thought experiment.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}