project:
  type: website

website:
  title: "Adventures of a self-learning data scientist"
  navbar:
    right:
      - studies.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/mitsuoxv
      - icon: twitter
        href: https://twitter.com/mitsuoxv
  google-analytics:
    tracking-id: "G-R04P6XVLCC"
    storage: none
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

