baseurl = "https://mitsuoxv.rbind.io/"
languageCode = "en-us"
title = "Adventures of a self-learning data scientist"
theme = "hugo-lithium"
googleAnalytics = "UA-162749034-1"
disqusShortname = ""


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Studies"
    url = "/studies/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mitsuoxv"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/mitsuoxv"

[params]
    description = "Economic analysis using R, tidyverse, etc."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

