---
title: Dark side of fiscal soundness advocacy
author: Mitsuo Shiota
date: '2021-06-05'
categories:
  - economics
  - Nikkei
---

I felt relieved when I read the guest essay ["Is the government bond a burden of future generations?" by Kazuo Momma, an ex-central banker, in the corner named "Economist 360 degree view point" of Nikkei newspaper on June 4, 2021 (Japanese, subscription required)](https://www.nikkei.com/article/DGXZQOCD286WU0Y1A520C2000000/), as it points out correctly that the government bond is both an asset and a liability. I would like to show my thumbs up to Nikkei for this article.

I felt depressed when I found a book by Prof. Kazumasa Oguro, to whom I referred as a fiscal soundness advocate in [the previous post](https://mitsuoxv.rbind.io/posts/2021-05-19-don-t-be-afraid-of-negative-real-interest-rates-by-inflation/). The book includes an interview with Prof. Kazumasa Oguro, who is credited as a co-author. The book was actually written and published by a scammer, who targets the wealthy, infuses them with aftermath images of a fiscal collapse, and invites them to his investment club with hefty fees. I will not name him here, but you can search if you can read Japanese. Prof. Kazumasa Oguro, be aware that your crying wolf is a good advertisement for a scammer.
