---
title: Yellen Dashboard
author: Mitsuo Shiota
date: '2019-04-25'
categories:
  - economics
  - R
---

As a statistics learner, I hate time series data, because it requires me to take more caution, like stationarity, than cross sectional data. As a R learner, I also hate time series data, because I have to learn other packages than tidyverse. As most economic data are time series, I have to find some way.

Then I have found [tidyquant package](https://cran.r-project.org/web/packages/tidyquant/vignettes/TQ02-quant-integrations-in-tidyquant.html). I am attracted by the function to download economic data from [FRED](https://fred.stlouisfed.org/), and the concept of long format data frame with 3 columns, "date", "symbol" and "price".

So I try it, and have made ["yellen-dashboard"](https://github.com/mitsuoxv/yellen-dashboard) in my GitHub repos. This shows the dashboard of US labor market charts, which Janet Yellen, former Fed chair, was said to be watching. As I can easily update the dashboard, I can be more frequently bothered to guess Fed's next move.

