---
title: The most (least) euro-ic country is Greece (Ireland)
author: Mitsuo Shiota
date: '2019-04-25'
categories:
  - economics
  - R
---

I often read "European (EU or Euro-area) economy is ...", but there are many countries there. So I have made charts of real GDP movements of each country in my GitHub repo ["euro-or-not-gdp"](https://github.com/mitsuoxv/euro-or-not-gdp). I paint different colors on the line depending on whether the country was in the euro area or not at each time point.

Next I have calculated the growth rates before and after the beginning of the financial crisis, and have plotted each country in y-axis of before growth rates and x-axis of after growth rates. The chart looks like a classifying task. So I have tried the classifier, logistic regression, and have got the possibility of each country to be in the euro-area at the beginning of the financial crisis. The highest probability euro country is Greece, and the lowest probability (so low as mis-classified as non-euro) euro country is Ireland.
