---
title: Don't be afraid of negative real interest rates by inflation
author: Mitsuo Shiota
date: '2021-05-19'
categories:
  - economics
  - NHK
  - Nikkei
---

I read some parts of the book ["Look deep into the fiscal crisis" (Japanese)](https://www.amazon.co.jp/%E8%B2%A1%E6%94%BF%E5%8D%B1%E6%A9%9F%E3%81%AE%E6%B7%B1%E5%B1%A4-%E5%A2%97%E7%A8%8E%E3%83%BB%E5%B9%B4%E9%87%91%E3%83%BB%E8%B5%A4%E5%AD%97%E5%9B%BD%E5%82%B5%E3%82%92%E5%95%8F%E3%81%86-NHK%E5%87%BA%E7%89%88%E6%96%B0%E6%9B%B8-%E5%B0%8F%E9%BB%92-%E4%B8%80%E6%AD%A3/dp/4140884495) more closely, and I've got what separates the author, Prof. Kazumasa Oguro, and me. That is whether negative real interest rates by inflation is intolerable or not.

I would like to show his position and mine in the context of the model I created in the last two posts ([here](https://mitsuoxv.rbind.io/2021/05/06/gov-t-debt-is-savings-of-the-workers-for-retirement/) and [here](https://mitsuoxv.rbind.io/2021/05/13/how-to-finance-war-against-godzilla/)).

## Model assumptions

I repeat the assumptions of the model below.

1. Our economy is a one factor (labor), three sector (Generation n (retired) and n+1 (working), Government) in Period n (30 years), and closed economy. There is no capital, no business sector, no international trade, and no foreigner. Ignore financial sector as an intermediary.

1. All goods and services produced in a Period are perishable, and must be consumed in that Period, like foodstuff and entertainment, care and medicine services. There is no stock, and no investment.

1. The only method for Generation n+1 (working) to save is to buy bonds.

1. The roles of Government are:

- to issue and pay back bonds, of which duration is one Period, 30 years,

- to supply national defense service against the natural disasters, such as flood, earthquake and pandemic, (as I assume no foreigner, there is no war against humans) and

- to collect tax.

## What I have learned from model simulations in the last two posts ([here](https://mitsuoxv.rbind.io/2021/05/06/gov-t-debt-is-savings-of-the-workers-for-retirement/) and [here](https://mitsuoxv.rbind.io/2021/05/13/how-to-finance-war-against-godzilla/)).

Note that the values in the model are not nominal, but real, and denominated in Period 1 price level yen. 

- When retired and working Generations agree how to share the produced other than defense spending (Government consumption), interest income of retired Generation and thus interest rates of holding bonds are determined endogenously in the model. Reversely, interest rates determine how to share buying power between retired and working Generations.

- Positive interest rates in the model can come not just from holding bonds but from tax and transfer, like an expansion of pay-go based pension system and an end of war-time tax. GDP growth through working population increase and productivity growth can contribute to positive interest rates.

- Negative interest rates can come not just from holding bonds but from tax and transfer, like a shrinkage of pay-go based pension system and an introduction of war-time tax. GDP decline through working population decrease and productivity stagnation can contribute to negative interest rates. Debt default and hyperinflation can also contribute to negative interest rates.

OK, I am ready to present his position and mine in the context of my model below. If I misrepresent his position, it is my fault.

## Prof. Kazumasa Oguro's position

- Negative interest rates mean that Government fails to pay back fully what it received 30 years ago in real terms, i.e. buying power terms. We should call this situation fiscal collapse. Debt default, hyperinflation and any other type of negative interest rates is intolerable.

- The U.K. employed "financial repression" to make interest rates artificially low by regulation and to make them less than inflation after the World War II ([Government debt to GDP ratio in the U.K. in my past post](https://mitsuoxv.rbind.io/2020/10/28/my-first-pull-request-imfr/)). This should be regarded as fiscal collapse.

- As GDP other than defense spending, i.e. the pie to share, is likely to shrink in the next Period 5 (2030-60, according to [my previous post](https://mitsuoxv.rbind.io/2021/05/06/gov-t-debt-is-savings-of-the-workers-for-retirement/)), Generation 5, who is working in the current Period 4 (2000-30) and will be retired in the next Period 5, must save less to avoid negative interest rates in next Period 5. It is equivalent to say that Generation 4, who is retired now, must consume less in the current Period 4 and/or Government have less deficits. So, tax Generation 4 and reduce Government deficits, now.

- The Abe administration's decision to postpone the consumption tax increase scheduled in October, 2015 was a big mistake. It made fiscal collapse more likely.

- The reasons why Government does not accept my proposal to tax Generation 4 now are:

 - Government is too optimistic about GDP in the next Period 5 (2030-60). So we need independent fiscal institutions to present unbiased long term economic forecasts.
 
 - Generation 4 outnumbers Generation 5, and exerts political power to avoid tax increases. So "Silver Democracy" is an obstacle.

## My position

- While debt default and hyperinflation is intolerable, negative real interest rates by inflation is tolerable, when we consider the costs. As positive real interest rates are the norm under increasing GDP, negative real interest rates are the norm under decreasing GDP.

- As for the U.K. experience after the World War II, I regard it as a success.

- We should think inter Generation equity from the viewpoint of not avoiding any type of negative real interest rates, but fair share in each Period and fair distribution of income in life by Generation.

- There are lucky and unlucky Generations, as population bonus and onus, productivity growth and stagnation, and war against Godzilla brings about both windfall and undue pains. So what I mean by "fair" is not quantitatively definitive in advance but politically decided afterwards.

- Although I agree that GDP is likely to shrink in the next Period 5 (2030-60), it is far from certain. Even if independent fiscal institutions can present unbiased long term economic forecasts, forecasts are always with a lot of uncertainties, especially when the time span is 30 years. The reason why Government does not accept his proposal to tax Generation 4 now is probably not because of Generation 4's greed and "Silver Democracy" but because of this uncertainty.

- A rigid rule to make "expected" buying power equal among Generations can result in a very unequal "actual" buying power distribution, and can be a burdensome legacy for future Generations.

- The Abe administration's decision to raise the consumption tax rate from 5 to 8 percent in April, 2014 was a big mistake. We should avoid austerity, when the resources are not fully utilized. This is a business cycle stabilization issue whose time span is less than 5 years. Due to this mistake, inflation momentum from high pressure economy was lost, and the Bank of Japan still fails to achieve its inflation target of 2 percent, which is foremost important to get negative real interest rates in an orderly manner.

- Embrace negative real interest rates by inflation. To get that, create high pressure economy through expansionary fiscal and monetary policies, so that the Bank of Japan can achieve its inflation target.

FULL DISCLOSURE: I retired at the end of February this year.
